name: crear-rama-release
on:
  push:
    branches: [ '*' ]
jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      palabra-found: ${{ steps.check_message.outputs.keyword_found }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message for keyword
      id: check_message
      run: |
        if [[ "${{ contains(github.event.head_commit.message, 'release') }}" == "true" ]]; then
          echo "Keyword found"
          echo "::set-output name=keyword_found::true"
        else
          echo "Keyword not found"
          echo "::set-output name=keyword_found::false"
        fi

  next-job:
    needs: check-commit-message
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir
      id: imprimir
      run: echo ${{needs.check-commit-message.outputs.keyword_found}}
    - name: Print OK
      if: needs.check-commit-message.outputs.keyword_found == 'true'
      run: echo "ok"
      



    
