name: crear-rama-release
on:
  push:
    branches: [ '*' ]
jobs:
  validar-palabra-clave:
    name: Validar palabra clave
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release')
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v2
    - name: Validar palabra clave
      id: check_message
      run: |
        if [[ "${{ contains(github.event.head_commit.message, 'release') }}" == "true" ]]; then
          echo "Keyword found"
          echo "::set-output name=keyword_found::true"
        else
          echo "Keyword not found"
          echo "::set-output name=keyword_found::false"
        fi



  next-job:
    needs: validar-palabra-clave
    runs-on: ubuntu-latest
    if: needs.validar-palabra-clave.outputs.keyword_found == 'true'
    steps:
      - name: Print OK
        run: echo "ok"
      



    
