name: crear-rama-release
on:
  push:
    branches: [ '*' ]
jobs:
  job1:
    name: Validar integracion
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release')
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: imprimir mensaje
      run: echo " Se activo porque llego palabra release"


    - name: Create release branch
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        RELEASE_BRANCH="release-prueba2"
        git checkout -b $RELEASE_BRANCH
        git push origin $RELEASE_BRANCH
    - name: Merge develop into release
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout release-prueba2
        git pull origin desarrollo --no-commit --no-ff
        git merge --no-ff --no-commit origin/develop || true
        git commit -m "Merge develop into feature-prueba2"
        git push origin feture-prueba2

      



    
