name: crear-rama-release
on:
  push:
    branches: [ '*' ]
jobs:
  validar-palabra-commit:
    runs-on: ubuntu-latest
    outputs:
      palabra: ${{ steps.buscar_palabra.outputs.palabra }}
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v2

    - name: buscar palabra en mensaje
      id: buscar_palabra
      run: |
        if [[ "${{ contains(github.event.head_commit.message, 'release') }}" == "true" ]]; then
          echo "Palabra encontrada"
          echo "::set-output name=palabra::true"
        else
          echo "Palabra no encontrada"
          echo "::set-output name=palabra::false"
        fi

  crear-rama-release:
    needs: validar-palabra-commit
    runs-on: ubuntu-latest
    if: needs.validar-palabra-commit.outputs.palabra == 'true' 
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2

    - name: Crear rama release
      id: crear_release
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        RELEASE_BRANCH="release-$(date +'%Y%m%d%H%M%S')"
        echo "nueva rama $RELEASE_BRANCH"
        git checkout -b $RELEASE_BRANCH
        git push origin $RELEASE_BRANCH

    - name: Merge develop en release
      run: |
        echo "variable $RELEASE_BRANCH"
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout $RELEASE_BRANCH
        git pull origin desarrollo --no-commit --no-ff --allow-unrelated-histories
        git merge --no-ff --no-commit origin/desarrollo
        git commit -m "Merge develop into $RELEASE_BRANCH"
        git push origin $RELEASE_BRANCH
      



    
