name: crear-rama-release
on:
  push:
    branches: [ '*' ]
jobs:
  validar-palabra-commit:
    runs-on: ubuntu-latest
    outputs:
      palabra: ${{ steps.buscar_palabra.outputs.palabra }}
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v2

    - name: buscar palabra en mensaje
      id: buscar_palabra
      run: |
        if [[ "${{ contains(github.event.head_commit.message, 'release') }}" == "true" ]]; then
          echo "Palabra encontrada"
          echo "::set-output name=palabra::true"
        else
          echo "Palabra no encontrada"
          echo "::set-output name=palabra::false"
        fi

  crear-rama-release:
    needs: validar-palabra-commit
    runs-on: ubuntu-latest
    if: needs.validar-palabra-commit.outputs.palabra == 'true' 
    steps:
    - name: Imprimir
      id: imprimir
      run: echo ${{needs.validar-palabra-commit.outputs.palabra}}
    - name: Print OK
      if: needs.validar-palabra-commit.outputs.palabra == 'true'
      run: echo "ok"
      



    
