name: crear-rama-release
on:
  push:
    branches: [ '*' ]
jobs:
  job1:
    name: Validar integracion
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release')
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: imprimir mensaje
      run: echo " Se activo porque llego palabra release"


    - name: Create release branch
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        RELEASE_BRANCH="release-$(date +'%Y%m%d%H%M%S')"
        git checkout -b $RELEASE_BRANCH
        git push origin $RELEASE_BRANCH
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ needs.create-release-branch.outputs.RELEASE_BRANCH }}
    - name: Merge develop into release
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout ${{ needs.create-release-branch.outputs.RELEASE_BRANCH }}
        git merge origin/develop
        git push origin ${{ needs.create-release-branch.outputs.RELEASE_BRANCH }}

      



    
