name: crear-rama-release
on:
  push:
    branches: [ '*' ]
jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message for keyword
      id: check_message
      run: |
        if [[ "${{ contains(github.event.head_commit.message, 'release') }}" == "true" ]]; then
          echo "Keyword found"
          echo "keyword_found=true" >> $GITHUB_ENV
        else
          echo "Keyword not found"
          echo "keyword_found=false" >> $GITHUB_ENV
        fi

  next-job:
    needs: check-commit-message
    runs-on: ubuntu-latest
    if: env.keyword_found == 'true'
    steps:
    - name: Print OK
      run: echo "ok"
      



    
